package com.ayfri.yologen

import net.minecraft.world.entity.EntityType

// Ordered list - index IS the YOLO class ID. Never reorder existing entries; append new mobs at the end of their section.
val MOB_TYPES = listOf(
	// Hostile
	EntityType.BLAZE,
	EntityType.BOGGED,
	EntityType.BREEZE,
	EntityType.CAVE_SPIDER,
	EntityType.CREAKING,
	EntityType.CREEPER,
	EntityType.DROWNED,
	EntityType.ELDER_GUARDIAN,
	EntityType.ENDERMAN,
	EntityType.ENDERMITE,
	EntityType.EVOKER,
	EntityType.GHAST,
	EntityType.GUARDIAN,
	EntityType.HOGLIN,
	EntityType.HUSK,
	EntityType.ILLUSIONER,
	EntityType.MAGMA_CUBE,
	EntityType.PARCHED,
	EntityType.PHANTOM,
	EntityType.PIGLIN,
	EntityType.PIGLIN_BRUTE,
	EntityType.PILLAGER,
	EntityType.RAVAGER,
	EntityType.SHULKER,
	EntityType.SILVERFISH,
	EntityType.SKELETON,
	EntityType.SLIME,
	EntityType.SPIDER,
	EntityType.STRAY,
	EntityType.VEX,
	EntityType.VINDICATOR,
	EntityType.WARDEN,
	EntityType.WITCH,
	EntityType.WITHER_SKELETON,
	EntityType.ZOGLIN,
	EntityType.ZOMBIE,
	EntityType.ZOMBIE_VILLAGER,
	EntityType.ZOMBIFIED_PIGLIN,

	// Neutral
	EntityType.BEE,
	EntityType.DOLPHIN,
	EntityType.GOAT,
	EntityType.IRON_GOLEM,
	EntityType.LLAMA,
	EntityType.PANDA,
	EntityType.POLAR_BEAR,
	EntityType.STRIDER,
	EntityType.TRADER_LLAMA,
	EntityType.WOLF,

	// Passive
	EntityType.ALLAY,
	EntityType.ARMADILLO,
	EntityType.AXOLOTL,
	EntityType.BAT,
	EntityType.CAMEL,
	EntityType.CAMEL_HUSK,
	EntityType.CAT,
	EntityType.CHICKEN,
	EntityType.COD,
	EntityType.COW,
	EntityType.DONKEY,
	EntityType.FOX,
	EntityType.FROG,
	EntityType.GLOW_SQUID,
	EntityType.HAPPY_GHAST,
	EntityType.HORSE,
	EntityType.MOOSHROOM,
	EntityType.MULE,
	EntityType.NAUTILUS,
	EntityType.OCELOT,
	EntityType.PARROT,
	EntityType.PIG,
	EntityType.PUFFERFISH,
	EntityType.RABBIT,
	EntityType.SALMON,
	EntityType.SHEEP,
	EntityType.SKELETON_HORSE,
	EntityType.SNIFFER,
	EntityType.SNOW_GOLEM,
	EntityType.SQUID,
	EntityType.TADPOLE,
	EntityType.TROPICAL_FISH,
	EntityType.TURTLE,
	EntityType.ZOMBIE_HORSE,
	EntityType.ZOMBIE_NAUTILUS,

	// Bosses & Golems
	EntityType.COPPER_GOLEM,
	EntityType.ENDER_DRAGON,
	EntityType.GIANT,
	EntityType.WITHER,
)

val YOLO_CLASS_MAP = MOB_TYPES.mapIndexed { i, type -> type to i }.toMap()
