package com.ayfri.yologen

import net.minecraft.world.entity.EntityType

val YOLO_CLASS_MAP = mapOf(
    // Hostile
    EntityType.BLAZE to 0,
    EntityType.BOGGED to 1,
    EntityType.BREEZE to 2,
    EntityType.CAVE_SPIDER to 3,
    EntityType.CREAKING to 4,
    EntityType.CREEPER to 5,
    EntityType.DROWNED to 6,
    EntityType.ELDER_GUARDIAN to 7,
    EntityType.ENDERMAN to 8,
    EntityType.ENDERMITE to 9,
    EntityType.EVOKER to 10,
    EntityType.GHAST to 11,
    EntityType.GUARDIAN to 12,
    EntityType.HOGLIN to 13,
    EntityType.HUSK to 14,
    EntityType.ILLUSIONER to 15,
    EntityType.MAGMA_CUBE to 16,
    EntityType.PARCHED to 17,
    EntityType.PHANTOM to 18,
    EntityType.PIGLIN to 19,
    EntityType.PIGLIN_BRUTE to 20,
    EntityType.PILLAGER to 21,
    EntityType.RAVAGER to 22,
    EntityType.SHULKER to 23,
    EntityType.SILVERFISH to 24,
    EntityType.SKELETON to 25,
    EntityType.SLIME to 26,
    EntityType.SPIDER to 27,
    EntityType.STRAY to 28,
    EntityType.VEX to 29,
    EntityType.VINDICATOR to 30,
    EntityType.WARDEN to 31,
    EntityType.WITCH to 32,
    EntityType.WITHER_SKELETON to 33,
    EntityType.ZOGLIN to 34,
    EntityType.ZOMBIE to 35,
    EntityType.ZOMBIE_VILLAGER to 36,
    EntityType.ZOMBIFIED_PIGLIN to 37,

    // Neutral
    EntityType.BEE to 38,
    EntityType.DOLPHIN to 39,
    EntityType.GOAT to 40,
    EntityType.IRON_GOLEM to 41,
    EntityType.LLAMA to 42,
    EntityType.PANDA to 43,
    EntityType.POLAR_BEAR to 44,
    EntityType.STRIDER to 45,
    EntityType.TRADER_LLAMA to 46,
    EntityType.WOLF to 47,

    // Passive
    EntityType.ALLAY to 48,
    EntityType.ARMADILLO to 49,
    EntityType.AXOLOTL to 50,
    EntityType.BAT to 51,
    EntityType.CAMEL to 52,
    EntityType.CAMEL_HUSK to 53,
    EntityType.CAT to 54,
    EntityType.CHICKEN to 55,
    EntityType.COD to 56,
    EntityType.COW to 57,
    EntityType.DONKEY to 58,
    EntityType.FOX to 59,
    EntityType.FROG to 60,
    EntityType.GLOW_SQUID to 61,
    EntityType.HAPPY_GHAST to 62,
    EntityType.HORSE to 63,
    EntityType.MOOSHROOM to 64,
    EntityType.MULE to 65,
    EntityType.NAUTILUS to 66,
    EntityType.OCELOT to 67,
    EntityType.PARROT to 68,
    EntityType.PIG to 69,
    EntityType.PUFFERFISH to 70,
    EntityType.RABBIT to 71,
    EntityType.SALMON to 72,
    EntityType.SHEEP to 73,
    EntityType.SKELETON_HORSE to 74,
    EntityType.SNIFFER to 75,
    EntityType.SNOW_GOLEM to 76,
    EntityType.SQUID to 77,
    EntityType.TADPOLE to 78,
    EntityType.TROPICAL_FISH to 79,
    EntityType.TURTLE to 80,
    EntityType.ZOMBIE_HORSE to 81,
    EntityType.ZOMBIE_NAUTILUS to 82,

    // Bosses & Golems
    EntityType.COPPER_GOLEM to 83,
    EntityType.ENDER_DRAGON to 84,
    EntityType.GIANT to 85,
    EntityType.WITHER to 86,
)
